CREATE TABLE IF NOT EXISTS users
(
    id         SERIAL,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    CONSTRAINT pk_users PRIMARY KEY (id),
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS users_roles
(
    role_id INT NOT NULL,
    user_id INT NOT NULL
);

ALTER TABLE IF EXISTS users_roles
    ADD CONSTRAINT fk_users_roles_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE IF EXISTS users_roles
    ADD CONSTRAINT fk_users_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);

CREATE TABLE IF NOT EXISTS users_info
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    phone      VARCHAR(255),
    last_name  VARCHAR(50),
    first_name VARCHAR(50),
    birthday   TIMESTAMP DEFAULT NOW(),
    sex        INTEGER,
    CONSTRAINT pk_users_info PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS users_info
    ADD CONSTRAINT fk_users_info_on_user FOREIGN KEY (user_id) REFERENCES users (id);